$modelname "snowysnowtime/vuthakral/c_hum_Mauler.mdl"

$bodygroup "magnum"
{
	studio "c_hum_Mauler.smd"
}

$include "c_hum_mauler_lod.qci"

$surfaceprop "weapon"

$contents "solid"

$illumposition -1.066 -15.931 -15.245

$cdmaterials "snowysnowtime/2k/vmt/h3"

$attachment "muzzle" "gun" 8 0 2.7 rotate 0 0 0

// $include "c_hum_mauler_box.qci"

$include "c_hum_mauler_bone.qci"

$include "c_hum_mauler_animation.qci"
