// Created by Crowbar 0.62

$modelname "halomodels/haloce/w_type25pistol.mdl"

$bodygroup "studio"
{
	studio "w_type25pistol_reference.smd"
}

$include "w_type25pistol_lod.qci"

$surfaceprop "weapon"

$contents "solid"

$illumposition 0.87 0.565 -2.736

$cdmaterials "models\weapons\w_plasmapistol\"

// $include "w_type25pistol_box.qci"

$include "w_type25pistol_bone.qci"

$include "w_type25pistol_animation.qci"

$include "w_type25pistol_collision.qci"
