// Created by Crowbar 0.62

$modelname "halomodels/haloce/w_type33.mdl"

$bodygroup "studio"
{
	studio "w_type33_reference.smd"
}

$include "w_type33_lod.qci"

$surfaceprop "weapon"

$contents "solid"

$illumposition 0.679 0.042 -2.092

$cdmaterials "models\weapons\w_needler\"

// $include "w_type33_box.qci"

$include "w_type33_bone.qci"

$include "w_type33_animation.qci"

$include "w_type33_collision.qci"
